"""emergency conditions and emergency events

Revision ID: f9548effea96
Revises: 2c9a7b1f3d55
Create Date: 2026-04-08 10:32:27.628130
"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'f9548effea96'
down_revision = '2c9a7b1f3d55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergency_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condition', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emergency',
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('id_emergency_condition', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_emergency_condition'], ['emergency_conditions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emergency')
    op.drop_table('emergency_conditions')
    # ### end Alembic commands ###
