"""add ended_at for emergency events

Revision ID: 0b94798d81c5
Revises: 0f7a24e972ce
Create Date: 2026-04-08 11:42:03.630941
"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '0b94798d81c5'
down_revision = '0f7a24e972ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emergency', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ended_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emergency', schema=None) as batch_op:
        batch_op.drop_column('ended_at')

    # ### end Alembic commands ###
