"""add name and soft delete for emergency conditions

Revision ID: 0f7a24e972ce
Revises: f9548effea96
Create Date: 2026-04-08 11:08:12.018546
"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '0f7a24e972ce'
down_revision = 'f9548effea96'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emergency_conditions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emergency_conditions', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
