"""auto migration

Revision ID: 1d48886d4130
Revises: 0001_initial_schema
Create Date: 2026-04-06 15:05:38.930980
"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '1d48886d4130'
down_revision = '0001_initial_schema'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
