"""strict migrations mode

Revision ID: 777e8d705140
Revises: 1d48886d4130
Create Date: 2026-04-06 15:41:41.567471
"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '777e8d705140'
down_revision = '1d48886d4130'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
